name: montra_app
description: "A new Flutter project."


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  lottie: ^3.1.2
  

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0


flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/lottie/
    - assets/vectors/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Black.ttf
        - asset: assets/fonts/inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/inter/Inter-ExtraBold.ttf
          weight: 800     
        - asset: assets/fonts/inter/Inter-ExtraLight.ttf
          weight: 200      
        - asset: assets/fonts/inter/Inter-Light.ttf
          weight: 300     
        - asset: assets/fonts/inter/Inter-Medium.ttf
          weight: 500  
        - asset: assets/fonts/inter/Inter-Regular.ttf
          weight: 400  
        - asset: assets/fonts/inter/Inter-SemiBold.ttf
          weight: 600   
        - asset: assets/fonts/inter/Inter-Thin.ttf
          weight: 100
        
         
         
        
        
        
        
